apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-medusa
  namespace: {{ .Values.storeName }}
  labels:
    app: medusa
    store: {{ .Values.storeName }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: medusa
    store: {{ .Values.storeName }}