apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storeName }}-postgresql-pvc
  namespace: {{ .Values.storeName }}
  labels:
    app: postgresql
    store: {{ .Values.storeName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storeName }}-medusa-pvc
  namespace: {{ .Values.storeName }}
  labels:
    app: medusa
    store: {{ .Values.storeName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.medusaPersistence.size }}
  {{- if .Values.medusaPersistence.storageClass }}
  storageClassName: {{ .Values.medusaPersistence.storageClass }}
  {{- end }}