apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storeName }}-postgresql-secret
  namespace: {{ .Values.storeName }}
  labels:
    app: postgresql
    store: {{ .Values.storeName }}
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc }}