apiVersion: v1
kind: Secret
metadata:
  name: store-service-secrets
  namespace: store-platform
type: Opaque
stringData:
  DB_PASSWORD: "MUSd1j9cCZ"
  VAULT_TOKEN: "root"  # For local dev only - in production use Vault Agent sidecar
  REDIS_PASSWORD: "redis_password_local"
